name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: '22'
    - run: |
        npm ci
        npm run build
        npx @vscode/vsce@latest package
      env:
        CI: true
    - uses: actions/upload-artifact@v7
      with:
        name: lime-vscode-extension
        path: lime-vscode-extension-*.vsix
        archive: false
        if-no-files-found: error
